In [2]:
import numpy as np
import pandas as pd
import os

# -------------------------------------------------
# STEP 1 — Define Tamil Nadu Bounding Box
# -------------------------------------------------
lat_min, lat_max = 8.0, 13.5
lon_min, lon_max = 76.0, 80.5

# Create 5 x 6 grid (30 spatial points)
lat_points = np.linspace(lat_min, lat_max, 5)
lon_points = np.linspace(lon_min, lon_max, 6)

grid = []

for lat in lat_points:
    for lon in lon_points:
        grid.append((round(lat, 4), round(lon, 4)))

grid_df = pd.DataFrame(grid, columns=["Latitude", "Longitude"])

# -------------------------------------------------
# STEP 2 — Save to MAIN project data folder
# -------------------------------------------------

# Get absolute project root (one level up from notebooks)
project_root = os.path.abspath("..")

# Create main data folder if not exists
data_folder = os.path.join(project_root, "data")
os.makedirs(data_folder, exist_ok=True)

# Save grid file
file_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df.to_csv(file_path, index=False)

print("✅ Grid created successfully.")
print("📁 Saved at:", file_path)

grid_df.head()

✅ Grid created successfully.
📁 Saved at: /Users/viki/Desktop/smart-irrigation-xai/data/tamilnadu_grid_points.csv

   Latitude  Longitude
0       8.0       76.0
1       8.0       76.9
2       8.0       77.8
3       8.0       78.7
4       8.0       79.6

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
# -------------------------------------------------
# STEP 1 — Define Tamil Nadu Bounding Box
# -------------------------------------------------
lat_min, lat_max = 8.0, 13.5
lon_min, lon_max = 76.0, 80.5

In [3]:
# Create 5 x 6 grid (30 spatial points)
lat_points = np.linspace(lat_min, lat_max, 5)
lon_points = np.linspace(lon_min, lon_max, 6)

grid = []

for lat in lat_points:
    for lon in lon_points:
        grid.append((round(lat, 4), round(lon, 4)))

grid_df = pd.DataFrame(grid, columns=["Latitude", "Longitude"])

In [4]:
# -------------------------------------------------
# STEP 2 — Save to MAIN project data folder
# -------------------------------------------------

# Get absolute project root (one level up from notebooks)
project_root = os.path.abspath("..")

In [5]:
# Create main data folder if not exists
data_folder = os.path.join(project_root, "data")
os.makedirs(data_folder, exist_ok=True)

In [6]:
# Save grid file
file_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df.to_csv(file_path, index=False)

In [7]:
print("✅ Grid created successfully.")
print("📁 Saved at:", file_path)

✅ Grid created successfully.
📁 Saved at: /Users/viki/Desktop/smart-irrigation-xai/data/tamilnadu_grid_points.csv

In [8]:
grid_df.head()

   Latitude  Longitude
0       8.0       76.0
1       8.0       76.9
2       8.0       77.8
3       8.0       78.7
4       8.0       79.6