In [3]:
import pandas as pd
import requests
import os
import time

# ----------------------------------------
# STEP 1 — Load Grid Points
# ----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

grid_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df = pd.read_csv(grid_path)

print("Loaded grid points:", len(grid_df))


# ----------------------------------------
# STEP 2 — Define Time Range
# ----------------------------------------

start = "20200101"
end = "20241231"


# ----------------------------------------
# STEP 3 — Loop Through Each Location
# ----------------------------------------

all_data = []

for index, row in grid_df.iterrows():
    
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    
    print(f"Fetching climate for: {latitude}, {longitude}")
    
    url = (
        "https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"parameters=T2M,RH2M,PRECTOTCORR"
        f"&community=AG"
        f"&longitude={longitude}"
        f"&latitude={latitude}"
        f"&start={start}"
        f"&end={end}"
        f"&format=JSON"
    )
    
    try:
        response = requests.get(url, timeout=30)
        data = response.json()
        
        climate_data = data["properties"]["parameter"]
        
        df = pd.DataFrame({
            "Date": climate_data["T2M"].keys(),
            "Temperature": climate_data["T2M"].values(),
            "Humidity": climate_data["RH2M"].values(),
            "Rainfall": climate_data["PRECTOTCORR"].values()
        })
        
        df["Latitude"] = latitude
        df["Longitude"] = longitude
        
        all_data.append(df)
        
        time.sleep(1)  # prevent API overload
        
    except Exception as e:
        print("Error at location:", latitude, longitude)
        print(e)


# ----------------------------------------
# STEP 4 — Combine All Locations
# ----------------------------------------

master_df = pd.concat(all_data, ignore_index=True)

master_df["Date"] = pd.to_datetime(master_df["Date"])

print("Final dataset shape:", master_df.shape)


# ----------------------------------------
# STEP 5 — Save to Project Data Folder
# ----------------------------------------

output_path = os.path.join(data_folder, "multi_location_climate_data.csv")
master_df.to_csv(output_path, index=False)

print("✅ Climate dataset saved at:", output_path)

master_df.head()

Loaded grid points: 30
Fetching climate for: 8.0, 76.0
Fetching climate for: 8.0, 76.9
Fetching climate for: 8.0, 77.8
Fetching climate for: 8.0, 78.7
Fetching climate for: 8.0, 79.6
Fetching climate for: 8.0, 80.5
Fetching climate for: 9.375, 76.0
Fetching climate for: 9.375, 76.9
Fetching climate for: 9.375, 77.8
Fetching climate for: 9.375, 78.7
Fetching climate for: 9.375, 79.6
Fetching climate for: 9.375, 80.5
Fetching climate for: 10.75, 76.0
Fetching climate for: 10.75, 76.9
Fetching climate for: 10.75, 77.8
Fetching climate for: 10.75, 78.7
Fetching climate for: 10.75, 79.6
Fetching climate for: 10.75, 80.5
Fetching climate for: 12.125, 76.0
Fetching climate for: 12.125, 76.9
Fetching climate for: 12.125, 77.8
Fetching climate for: 12.125, 78.7
Fetching climate for: 12.125, 79.6
Fetching climate for: 12.125, 80.5
Fetching climate for: 13.5, 76.0
Fetching climate for: 13.5, 76.9
Fetching climate for: 13.5, 77.8
Fetching climate for: 13.5, 78.7
Fetching climate for: 13.5, 79.6
Fetching climate for: 13.5, 80.5
Final dataset shape: (54810, 6)
✅ Climate dataset saved at: /Users/viki/Desktop/smart-irrigation-xai/data/multi_location_climate_data.csv

        Date  Temperature  Humidity  Rainfall  Latitude  Longitude
0 2020-01-01        28.09     75.08      0.11       8.0       76.0
1 2020-01-02        28.36     75.44      0.63       8.0       76.0
2 2020-01-03        28.56     77.93      1.12       8.0       76.0
3 2020-01-04        28.17     78.82      3.46       8.0       76.0
4 2020-01-05        28.46     77.96      5.03       8.0       76.0

In [1]:
import pandas as pd
import requests
import os
import time

In [2]:
# ----------------------------------------
# STEP 1 — Load Grid Points
# ----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

grid_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df = pd.read_csv(grid_path)

print("Loaded grid points:", len(grid_df))

Loaded grid points: 30

In [3]:
# ----------------------------------------
# STEP 2 — Define Time Range
# ----------------------------------------

start = "20200101"
end = "20241231"

In [4]:
# ----------------------------------------
# STEP 3 — Loop Through Each Location
# ----------------------------------------

all_data = []

for index, row in grid_df.iterrows():
    
    latitude = row["Latitude"]
    longitude = row["Longitude"]
    
    print(f"Fetching climate for: {latitude}, {longitude}")
    
    url = (
        "https://power.larc.nasa.gov/api/temporal/daily/point?"
        f"parameters=T2M,RH2M,PRECTOTCORR"
        f"&community=AG"
        f"&longitude={longitude}"
        f"&latitude={latitude}"
        f"&start={start}"
        f"&end={end}"
        f"&format=JSON"
    )
    
    try:
        response = requests.get(url, timeout=30)
        data = response.json()
        
        climate_data = data["properties"]["parameter"]
        
        df = pd.DataFrame({
            "Date": climate_data["T2M"].keys(),
            "Temperature": climate_data["T2M"].values(),
            "Humidity": climate_data["RH2M"].values(),
            "Rainfall": climate_data["PRECTOTCORR"].values()
        })
        
        df["Latitude"] = latitude
        df["Longitude"] = longitude
        
        all_data.append(df)
        
        time.sleep(1)  # prevent API overload
        
    except Exception as e:
        print("Error at location:", latitude, longitude)
        print(e)

Fetching climate for: 8.0, 76.0
Fetching climate for: 8.0, 76.9
Fetching climate for: 8.0, 77.8
Fetching climate for: 8.0, 78.7
Fetching climate for: 8.0, 79.6
Fetching climate for: 8.0, 80.5
Fetching climate for: 9.375, 76.0
Fetching climate for: 9.375, 76.9
Fetching climate for: 9.375, 77.8
Fetching climate for: 9.375, 78.7
Fetching climate for: 9.375, 79.6
Fetching climate for: 9.375, 80.5
Fetching climate for: 10.75, 76.0
Fetching climate for: 10.75, 76.9
Fetching climate for: 10.75, 77.8
Fetching climate for: 10.75, 78.7
Fetching climate for: 10.75, 79.6
Fetching climate for: 10.75, 80.5
Fetching climate for: 12.125, 76.0
Fetching climate for: 12.125, 76.9
Fetching climate for: 12.125, 77.8
Fetching climate for: 12.125, 78.7
Fetching climate for: 12.125, 79.6
Fetching climate for: 12.125, 80.5
Fetching climate for: 13.5, 76.0
Fetching climate for: 13.5, 76.9
Fetching climate for: 13.5, 77.8
Fetching climate for: 13.5, 78.7
Fetching climate for: 13.5, 79.6
Fetching climate for: 13.5, 80.5

In [5]:
# ----------------------------------------
# STEP 4 — Combine All Locations
# ----------------------------------------

master_df = pd.concat(all_data, ignore_index=True)

master_df["Date"] = pd.to_datetime(master_df["Date"])

print("Final dataset shape:", master_df.shape)

Final dataset shape: (54810, 6)

In [6]:
# ----------------------------------------
# STEP 5 — Save to Project Data Folder
# ----------------------------------------

output_path = os.path.join(data_folder, "multi_location_climate_data.csv")
master_df.to_csv(output_path, index=False)

print("✅ Climate dataset saved at:", output_path)

master_df.head()

✅ Climate dataset saved at: /Users/viki/Desktop/smart-irrigation-xai/data/multi_location_climate_data.csv

        Date  Temperature  Humidity  Rainfall  Latitude  Longitude
0 2020-01-01        28.09     75.08      0.11       8.0       76.0
1 2020-01-02        28.36     75.44      0.63       8.0       76.0
2 2020-01-03        28.56     77.93      1.12       8.0       76.0
3 2020-01-04        28.17     78.82      3.46       8.0       76.0
4 2020-01-05        28.46     77.96      5.03       8.0       76.0