In [3]:
import pandas as pd
import os

# -----------------------------------------
# STEP 1 — Load Grid Points
# -----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

grid_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df = pd.read_csv(grid_path)

print("Total grid points:", len(grid_df))


# -----------------------------------------
# STEP 2 — FAO-Based Soil Assignment Logic
# -----------------------------------------

def assign_soil(lat, lon):
    
    # Coastal sandy soil (East coast)
    if lon > 79.5:
        return "Sandy"
    
    # Western black soil belt
    elif lon < 77.5:
        return "Black"
    
    # Southern lateritic / clay mix
    elif lat < 9.5:
        return "Clay"
    
    # Delta alluvial zone
    elif 78.5 < lon < 79.5 and 10 < lat < 11.5:
        return "Alluvial"
    
    # Default central red soil
    else:
        return "Red"


grid_df["Soil_Type"] = grid_df.apply(
    lambda row: assign_soil(row["Latitude"], row["Longitude"]), axis=1
)

print("Soil distribution:")
print(grid_df["Soil_Type"].value_counts())


# -----------------------------------------
# STEP 3 — Define Soil Retention Factors
# -----------------------------------------

soil_factor_map = {
    "Sandy": 1.25,     # Low retention → more irrigation
    "Red": 1.10,
    "Alluvial": 1.00,
    "Black": 0.90,
    "Clay": 0.85
}

grid_df["Soil_Factor"] = grid_df["Soil_Type"].map(soil_factor_map)


# -----------------------------------------
# STEP 4 — Save Soil Dataset
# -----------------------------------------

soil_path = os.path.join(data_folder, "soil_data.csv")
grid_df.to_csv(soil_path, index=False)

print("✅ FAO-based soil data saved at:", soil_path)

grid_df.head()

Total grid points: 30
Soil distribution:
Soil_Type
Black       10
Sandy       10
Red          5
Clay         4
Alluvial     1
Name: count, dtype: int64
✅ FAO-based soil data saved at: /Users/viki/Desktop/smart-irrigation-xai/data/soil_data.csv

   Latitude  Longitude Soil_Type  Soil_Factor
0       8.0       76.0     Black         0.90
1       8.0       76.9     Black         0.90
2       8.0       77.8      Clay         0.85
3       8.0       78.7      Clay         0.85
4       8.0       79.6     Sandy         1.25

In [1]:
import pandas as pd
import os

In [2]:
# -----------------------------------------
# STEP 1 — Load Grid Points
# -----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

grid_path = os.path.join(data_folder, "tamilnadu_grid_points.csv")
grid_df = pd.read_csv(grid_path)

print("Total grid points:", len(grid_df))

Total grid points: 30

In [3]:

# -----------------------------------------
# STEP 2 — FAO-Based Soil Assignment Logic
# -----------------------------------------

def assign_soil(lat, lon):
    
    # Coastal sandy soil (East coast)
    if lon > 79.5:
        return "Sandy"
    
    # Western black soil belt
    elif lon < 77.5:
        return "Black"
    
    # Southern lateritic / clay mix
    elif lat < 9.5:
        return "Clay"
    
    # Delta alluvial zone
    elif 78.5 < lon < 79.5 and 10 < lat < 11.5:
        return "Alluvial"
    
    # Default central red soil
    else:
        return "Red"


grid_df["Soil_Type"] = grid_df.apply(
    lambda row: assign_soil(row["Latitude"], row["Longitude"]), axis=1
)

print("Soil distribution:")
print(grid_df["Soil_Type"].value_counts())

Soil distribution:
Soil_Type
Black       10
Sandy       10
Red          5
Clay         4
Alluvial     1
Name: count, dtype: int64

In [4]:
# -----------------------------------------
# STEP 3 — Define Soil Retention Factors
# -----------------------------------------

soil_factor_map = {
    "Sandy": 1.25,     # Low retention → more irrigation
    "Red": 1.10,
    "Alluvial": 1.00,
    "Black": 0.90,
    "Clay": 0.85
}

grid_df["Soil_Factor"] = grid_df["Soil_Type"].map(soil_factor_map)

In [5]:
# -----------------------------------------
# STEP 4 — Save Soil Dataset
# -----------------------------------------

soil_path = os.path.join(data_folder, "soil_data.csv")
grid_df.to_csv(soil_path, index=False)

print("✅ FAO-based soil data saved at:", soil_path)

grid_df.head()

✅ FAO-based soil data saved at: /Users/viki/Desktop/smart-irrigation-xai/data/soil_data.csv

   Latitude  Longitude Soil_Type  Soil_Factor
0       8.0       76.0     Black         0.90
1       8.0       76.9     Black         0.90
2       8.0       77.8      Clay         0.85
3       8.0       78.7      Clay         0.85
4       8.0       79.6     Sandy         1.25