In [1]:
import pandas as pd
import numpy as np
import os

# -----------------------------------------
# STEP 1 — Load Climate Data
# -----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

climate_path = os.path.join(data_folder, "multi_location_climate_data.csv")
soil_path = os.path.join(data_folder, "soil_data.csv")

climate_df = pd.read_csv(climate_path)
soil_df = pd.read_csv(soil_path)

print("Climate shape:", climate_df.shape)
print("Soil shape:", soil_df.shape)


# -----------------------------------------
# STEP 2 — Merge Climate + Soil
# -----------------------------------------

merged_df = pd.merge(
    climate_df,
    soil_df,
    on=["Latitude", "Longitude"],
    how="left"
)

print("Merged shape:", merged_df.shape)


# -----------------------------------------
# STEP 3 — Convert Date
# -----------------------------------------

merged_df["Date"] = pd.to_datetime(merged_df["Date"])


# -----------------------------------------
# STEP 4 — Compute ET (Evapotranspiration)
# -----------------------------------------

merged_df["ET0"] = (
    0.5 * merged_df["Temperature"]
    - 0.3 * (merged_df["Humidity"] / 100)
)

merged_df["Water_mm"] = merged_df["ET0"] - merged_df["Rainfall"]

merged_df["Water_mm"] = merged_df["Water_mm"].apply(lambda x: max(0, x))


# -----------------------------------------
# STEP 5 — Convert to Liters per Hectare
# -----------------------------------------

merged_df["Water_Liters"] = merged_df["Water_mm"] * 10000


# -----------------------------------------
# STEP 6 — Apply Soil Retention Factor
# -----------------------------------------

merged_df["Water_Liters"] = (
    merged_df["Water_Liters"] * merged_df["Soil_Factor"]
)


# -----------------------------------------
# STEP 7 — Add Season Feature
# -----------------------------------------

def get_season(month):
    if month in [1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "SW_Monsoon"
    else:
        return "NE_Monsoon"

merged_df["Season"] = merged_df["Date"].dt.month.apply(get_season)


# -----------------------------------------
# STEP 8 — Final Clean Dataset
# -----------------------------------------

final_df = merged_df[
    [
        "Date",
        "Latitude",
        "Longitude",
        "Temperature",
        "Humidity",
        "Rainfall",
        "Season",
        "Soil_Type",
        "Water_Liters"
    ]
]

print("Final dataset shape:", final_df.shape)


# -----------------------------------------
# STEP 9 — Save Final Dataset
# -----------------------------------------

final_path = os.path.join(data_folder, "final_spatial_irrigation_dataset.csv")
final_df.to_csv(final_path, index=False)

print("✅ Final dataset saved at:", final_path)

final_df.head()

Climate shape: (54810, 6)
Soil shape: (30, 4)
Merged shape: (54810, 8)
Final dataset shape: (54810, 9)
✅ Final dataset saved at: /Users/viki/Desktop/smart-irrigation-xai/data/final_spatial_irrigation_dataset.csv

,Date,Latitude,Longitude,Temperature,Humidity,Rainfall,Season,Soil_Type,Water_Liters
0,2020-01-01,8.0,76.0,28.09,75.08,0.11,Winter,Black,123387.84
1,2020-01-02,8.0,76.0,28.36,75.44,0.63,Winter,Black,119913.12
2,2020-01-03,8.0,76.0,28.56,77.93,1.12,Winter,Black,116335.89
3,2020-01-04,8.0,76.0,28.17,78.82,3.46,Winter,Black,93496.86
4,2020-01-05,8.0,76.0,28.46,77.96,5.03,Winter,Black,80695.08

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# -----------------------------------------
# STEP 1 — Load Climate Data
# -----------------------------------------

project_root = os.path.abspath("..")
data_folder = os.path.join(project_root, "data")

climate_path = os.path.join(data_folder, "multi_location_climate_data.csv")
soil_path = os.path.join(data_folder, "soil_data.csv")

climate_df = pd.read_csv(climate_path)
soil_df = pd.read_csv(soil_path)

print("Climate shape:", climate_df.shape)
print("Soil shape:", soil_df.shape)

Climate shape: (54810, 6)
Soil shape: (30, 4)

In [3]:
# -----------------------------------------
# STEP 2 — Merge Climate + Soil
# -----------------------------------------

merged_df = pd.merge(
    climate_df,
    soil_df,
    on=["Latitude", "Longitude"],
    how="left"
)

print("Merged shape:", merged_df.shape)

Merged shape: (54810, 8)

In [4]:
# -----------------------------------------
# STEP 3 — Convert Date
# -----------------------------------------

merged_df["Date"] = pd.to_datetime(merged_df["Date"])

In [5]:
# -----------------------------------------
# STEP 4 — Compute ET (Evapotranspiration)
# -----------------------------------------

merged_df["ET0"] = (
    0.5 * merged_df["Temperature"]
    - 0.3 * (merged_df["Humidity"] / 100)
)

merged_df["Water_mm"] = merged_df["ET0"] - merged_df["Rainfall"]

merged_df["Water_mm"] = merged_df["Water_mm"].apply(lambda x: max(0, x))

In [6]:
# -----------------------------------------
# STEP 5 — Convert to Liters per Hectare
# -----------------------------------------

merged_df["Water_Liters"] = merged_df["Water_mm"] * 10000

In [7]:
# -----------------------------------------
# STEP 6 — Apply Soil Retention Factor
# -----------------------------------------

merged_df["Water_Liters"] = (
    merged_df["Water_Liters"] * merged_df["Soil_Factor"]
)

In [8]:
# -----------------------------------------
# STEP 7 — Add Season Feature
# -----------------------------------------

def get_season(month):
    if month in [1, 2]:
        return "Winter"
    elif month in [3, 4, 5]:
        return "Summer"
    elif month in [6, 7, 8, 9]:
        return "SW_Monsoon"
    else:
        return "NE_Monsoon"

merged_df["Season"] = merged_df["Date"].dt.month.apply(get_season)

In [9]:
# -----------------------------------------
# STEP 8 — Final Clean Dataset
# -----------------------------------------

final_df = merged_df[
    [
        "Date",
        "Latitude",
        "Longitude",
        "Temperature",
        "Humidity",
        "Rainfall",
        "Season",
        "Soil_Type",
        "Water_Liters"
    ]
]

print("Final dataset shape:", final_df.shape)

Final dataset shape: (54810, 9)

In [10]:

# -----------------------------------------
# STEP 9 — Save Final Dataset
# -----------------------------------------

final_path = os.path.join(data_folder, "final_spatial_irrigation_dataset.csv")
final_df.to_csv(final_path, index=False)

print("✅ Final dataset saved at:", final_path)

final_df.head()

✅ Final dataset saved at: /Users/viki/Desktop/smart-irrigation-xai/data/final_spatial_irrigation_dataset.csv

,Date,Latitude,Longitude,Temperature,Humidity,Rainfall,Season,Soil_Type,Water_Liters
0,2020-01-01,8.0,76.0,28.09,75.08,0.11,Winter,Black,123387.84
1,2020-01-02,8.0,76.0,28.36,75.44,0.63,Winter,Black,119913.12
2,2020-01-03,8.0,76.0,28.56,77.93,1.12,Winter,Black,116335.89
3,2020-01-04,8.0,76.0,28.17,78.82,3.46,Winter,Black,93496.86
4,2020-01-05,8.0,76.0,28.46,77.96,5.03,Winter,Black,80695.08